agent:
  # includes trailing whitespace to test trim
  yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    spec:
      tolerations:
      - key: "key"
        operator: "Equal"
        value: {{ .Values.tolerations }}
        
tolerations: 10
